/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package flightbooking.components.menu;

/**
 *
 * @author night
 */

import flightbooking.Main;
import flightbooking.components.NewFlight.NewFlightComponents;
import flightbooking.components.bookFlight.BookFlightComponents;
import flightbooking.components.bookFlight.BookFlightForm;
public class MenuForm extends javax.swing.JFrame {

    /**
     * Creates new form MenuForm
     */
    public MenuForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        viewFlight = new javax.swing.JButton();
        addFlight = new javax.swing.JButton();
        viewBookings = new javax.swing.JButton();
        bookFlightButton = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(441, 699));
        setMinimumSize(new java.awt.Dimension(441, 699));
        setPreferredSize(new java.awt.Dimension(280, 440));
        setResizable(false);
        setSize(new java.awt.Dimension(441, 699));

        jLayeredPane1.setMinimumSize(new java.awt.Dimension(441, 699));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewFlight.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        viewFlight.setText("View Flights");
        viewFlight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewFlightMouseClicked(evt);
            }
        });
        viewFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFlightActionPerformed(evt);
            }
        });
        jLayeredPane1.add(viewFlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 150, -1));

        addFlight.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        addFlight.setText("Add Flight");
        addFlight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addFlightMouseClicked(evt);
            }
        });
        jLayeredPane1.add(addFlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 150, -1));

        viewBookings.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        viewBookings.setText("View Bookings");
        viewBookings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewBookingsMouseClicked(evt);
            }
        });
        jLayeredPane1.add(viewBookings, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 560, 150, -1));

        bookFlightButton.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        bookFlightButton.setText("Book Flight");
        bookFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookFlightButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(bookFlightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 150, -1));

        Exit.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        Exit.setText("Exit");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        jLayeredPane1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 150, -1));

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jLayeredPane1.add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, -1, 450));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flightbooking/components/menu/logo.jpg"))); // NOI18N
        jLayeredPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 880));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bookFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookFlightButtonActionPerformed
        Main.newBookingObject();
        BookFlightForm.bookNum = BookFlightComponents.genBookNum();
        NewFlightComponents.addFlight = null;
        Main.showBookFlightForm();
        
        
    }//GEN-LAST:event_bookFlightButtonActionPerformed

    private void addFlightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addFlightMouseClicked
        Main.newFlightObject();
        BookFlightComponents.newBook = null;
        Main.showNewFlightForm();
   
        
    }//GEN-LAST:event_addFlightMouseClicked

    private void viewFlightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewFlightMouseClicked
        NewFlightComponents.addFlight = null;
        BookFlightComponents.newBook = null;
        Main.showViewFlight();
    }//GEN-LAST:event_viewFlightMouseClicked

    private void viewBookingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBookingsMouseClicked
        Main.showViewBooking();
    }//GEN-LAST:event_viewBookingsMouseClicked

    private void viewFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFlightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewFlightActionPerformed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton addFlight;
    private javax.swing.JButton bookFlightButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JButton viewBookings;
    private javax.swing.JButton viewFlight;
    // End of variables declaration//GEN-END:variables
}
